class Constants:
    TICK_RATE = 60
    SLOW_MOTION_TICK_RATE = 5
    TIME_STEP = 1.0 / TICK_RATE
    STICK_LENGTH = 4
    VEL_ITERS = 8
    POS_ITERS = 3
    TABLE_WIDTH = 9.0
    TABLE_HEIGHT = 4.5
    TABLE_RATIO = TABLE_WIDTH / TABLE_HEIGHT
    BALL_RADIUS = 2 / 12
    POCKET_RADIUS = 3 / 12
    WIDTH = 1280
    HEIGHT = WIDTH // 2
    CUE_BALL = 0